remote_theme: "mmistakes/so-simple-theme"

lang: en-GB
title: Library Data Camp 2019
email: info@datatreaders.co.uk
description: "Voyage of the Data Treader: Put your library on the map"
url: "https://www.datatreaders.co.uk"
logo: /assets/logo.jpg
search: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true
